[package]
name = "parallel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0"
criterion = {version = "0", features = ["html_reports"]}

[[bench]]
name = "m_sort_b"
harness = false